image: docker:latest
services:
- docker:dind

stages:
- build
- deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

  # https://gitlab.com/gitlab-org/gitlab-ce/issues/20367#note_89285011
  - touch .variables
  - ENV_VAR_SUFFIX="__${CI_ENVIRONMENT_SLUG}"; for var in $(env | awk -F "=" '{print $1}' | grep "${ENV_VAR_SUFFIX}$"); do echo 'export ${var%${ENV_VAR_SUFFIX}}="${!var}"' >> .variables; done 
  - echo ${CI_ENVIRONMENT_SLUG}
  - echo $CI_ENVIRONMENT_SLUG
  - echo ${ENV_VAR_SUFFIX}
  - cat .variables


Build:
  stage: build
  script:
    - source .variables
    - cat .variables
    - env
    - exit(0)
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME || echo Could not fetch $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME from registry.
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

Demo1:
  stage: deploy
  services:
    - docker:dind
  environment:
    name: demo1
    url: https://demo1.webcaptioner.com
  script:
    - source scripts/deploy.sh
  when: manual

Staging:
  stage: deploy
  services:
    - docker:dind
  environment:
    name: staging
    url: https://staging.webcaptioner.com
  script:
    - source scripts/deploy.sh

Production:
  stage: deploy
  services:
    - docker:dind
  environment:
    name: production
    url: https://webcaptioner.com
  script:
    - source scripts/deploy.sh
  when: manual